msualumni/msualumni/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin as dj_admin
from django.contrib.auth import views as auth_views

from portal.views import index, signup, activate, contact_profile
from msualumni import settings
from msualumni.utils import captcha

dj_admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include('alumniadmin.urls')),
    url(r'^django/', include(dj_admin.site.urls)),
    url(r'^news/', include('news.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^profiles/', include('profiles.urls')),

    url(r'^contact$', contact_profile),
    url(r'^signup$', signup),
    url(r'^activate$', activate),
    url(r'^logout$', auth_views.logout, {'next_page':'/login'}),
    url(r'^login/$',
        auth_views.login,
        {'template_name':'portal/login.html',
         'redirect_field_name':'/'
        }),
    url(r'^$', index),
    #url(r'^captcha/get_salt', captcha.get_salt),
)

urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

msualumni/news/msuadmin/urls.py
from django.conf.urls import patterns, include, url
from views import NewsFeed, WriteArticle, EditArticle, ReadArticle, ArticleYearArchive, ArticleMonthArchive


urlpatterns = patterns('',
	url(r'^write$', WriteArticle.as_view(), name="write-article"),
	url(r'^edit/(?P<id>\d+)/$', EditArticle.as_view(), name="admin-edit-article"),
	url(r'^read/(?P<pk>\d+)/$', ReadArticle.as_view(), name="admin-read-article"),
	url(r'^archives/(?P<year>\d{4})/$', ArticleYearArchive.as_view(), name="admin-year-archives"),
	url(r'^archives/(?P<year>\d{4})/(?P<month>\d+)/$', ArticleMonthArchive.as_view(), name="admin-month-archives"),
	)

msualumni/news/urls.py
from django.conf.urls import patterns, include, url
from views import NewsFeed, WriteArticle, ReadArticle, ArticleYearArchive, ArticleMonthArchive


urlpatterns = patterns('',
	url(r'^write$', WriteArticle.as_view(), name="write-article"),
	url(r'^read/(?P<pk>\d+)/$', ReadArticle.as_view(template_name="news/read_article.html"), name="read-article"),
	url(r'^archives/(?P<year>\d{4})/$', ArticleYearArchive.as_view(template_name="news/archives.html"), name="year-archives"),
	url(r'^archives/(?P<year>\d{4})/(?P<month>\d+)/$', ArticleMonthArchive.as_view(template_name="news/archives.html", month_format='%m'), name="year-archives"),
	url(r'^$', NewsFeed.as_view(), name="news-feed")
	)

msualumni/profiles/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from msuadmin import views as msu
from views import save_profile_details, AdvancedSearch, ProfileUpdateView, ProfileIndex, ProfileRequest, ProfileDetailView

urlpatterns = patterns ( '',
		url(r'^$', ProfileIndex.as_view(template_name="profiles/index.html"), name='client-profiles'),
		url(r'^(?P<slug>\d+)$', ProfileDetailView.as_view(), name="profile-page"),
		url(r'^request$', ProfileRequest.as_view()),
		url(r'^update/(?P<id>\d+)', ProfileUpdateView.as_view()),
		url(r'^save$', save_profile_details),
		url(r'^advanced$', AdvancedSearch.as_view()),
		url(r'^request/success$', TemplateView.as_view(template_name="portal/application_success.html")),
	)

msualumni/profiles/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template

CAMPUSES = (('MSU Marawi', 'MSU Marawi'),
            ('MSU Iligan (IIT)', 'MSU Iligan (IIT)'),
            ('MSU MSAT', 'MSU MSAT'), 
            ('MSU Naawan', 'MSU Naawan'), 
            ('MSU Sulu', 'MSU Sulu'), 
            ('MSU Tawi-Tawi', 'MSU Tawi-Tawi'), 
            ('MSU General Santos', 'MSU General Santos'), 
            ('MSU LNCAT', 'MSU LNCAT'), 
            ('MSU Buug', 'MSU Buug'), 
            ('MSU Maguindanao', 'MSU Maguindanao'), 
            ('MSU LNAC', 'MSU LNAC'))
STATUS = (('V', 'Verified'),
          ('A', 'Approved'),
          ('R', 'Rejected'),
          ('P', 'Pending'),)

DEGREES = (('BS', 'Bachelor of Science'),
           ('AB', 'Bachelor of Arts'),
           ('Diploma', 'Diploma'),
           ('Certificate', 'Certificate'),
           ('MA', 'Master of Arts'),
           ('MS', 'Master of Science'),
           ('D', 'Doctorate'))
#model for storing religion. we can't really be sure how many there are so we add a model for it.
class Religion(models.Model):
  
  
  name = models.CharField(max_length=54)
  
  def __unicode__(self):
    return self.name
  
  class Meta:
    db_table='religion'
    

#model for tribe. like religion, this could go from less than 30 to 100. client side should handle duplicates with ajax requests    
class Tribe(models.Model):
  
  
  name = models.CharField(max_length=32)
  
  def __unicode__(self):
    return self.name
    
  class Meta:
    db_table='tribe'
    


class City(models.Model):


  city = models.CharField(max_length=64)
  province = models.CharField(max_length=64)
  zip = models.CharField(max_length=16)
  country = models.CharField(max_length=64,  default="Philippines")
  
  def __unicode__(self):
    return u'%s, %s, %s' % (self.city, self.province, self.country)
  
  class Meta:
    db_table='city'
    verbose_name_plural='Cities'   
    unique_together=(('city', 'province'),)
    
    
#model for breaking down home addresses. this makes it easier to parse address information and make information discovery faster
class Residence(models.Model):

  
  street = models.CharField(max_length=64)
  barangay = models.CharField(max_length=64)
  city = models.ForeignKey(City)
  
  def __unicode__(self):
    return u'%s %s' % (self.street, self.barangay)

  class Meta:
    db_table='residence'

  
#model for breaking down current work
class BusinessAddress(models.Model):


  position = models.CharField(max_length=64, default="Unspecified")
  company = models.CharField(max_length=96, blank=True)
  city = models.ForeignKey(City)

  def __unicode__(self):
    return u'%s at %s' % (self.position, self.company)

  class Meta:
    db_table='business_address'
    verbose_name_plural='Business Addresses'
    verbose_name='Business Address'
    
#integration model for alumnus information    
class Alum(models.Model):

  
  alumni_id = models.CharField(max_length=12, primary_key=True)
  first_name = models.CharField(max_length=32)
  last_name = models.CharField(max_length=32)
  middle_name = models.CharField(max_length=32)
  email = models.EmailField(null=True, blank=True)
  mobile = models.CharField(max_length=12, null=True, blank=True)
  birthdate = models.DateField(null=True, blank=True)
  gender = models.CharField(max_length=6, null=True, blank=True)
  civil_status = models.CharField(max_length=8, null=True, blank=True)
  citizenship = models.CharField(max_length=32, null=True, blank=True)
  tribe = models.CharField(max_length=128, null=True, blank=True)
  religion = models.CharField(max_length=64, null=True, blank=True)
  residence = models.ForeignKey(Residence, null=True, blank=True)
  hometown = models.ForeignKey(City, null=True, blank=True)
  business_address = models.ForeignKey(BusinessAddress, null=True, blank=True)
  pic = models.ImageField(upload_to='media/profiles/', default='/media/profiles/default.png')
  date_created = models.DateTimeField(auto_now_add=True)
  date_modified = models.DateTimeField(auto_now_add=True, auto_now=True)
  is_active = models.BooleanField(default=False)
  
  def __unicode__(self):
    return u'%s %s' % (self.first_name, self.last_name)
  
  def get_full_name(self):
    """
      Returns the first name and last name of the alum separated with a space
    """
    full_name = u'%s %s'(self.first_name, self.last_name)
    return full_name.strip()

  def get_absolute_url(self):
    return "/profiles/"+self.alumni_id

  def send_email(self, subject, context, templates, from_email=None):
    if self.email:
      try:
        html = get_template(templates['html'])
        plaintext = get_template(templates['plaintext'])
      except KeyError:
        raise

      plaintext_content = plaintext.render(context)
      html_content = html.render(context)
      try:
        email = EmailMultiAlternatives(subject, plaintext_content, from_email, [self.email])
        email.attach_alternative(html_content, 'text/html')
        email.send()
      except:
        raise
    else:
      print "No email set!"

    
  class Meta:
    db_table='alum'
    verbose_name_plural='alumni'
    
class Campus(models.Model):

  
  name = models.CharField(max_length=64)
  
  def __unicode__(self):
    return self.name
    
  class Meta:
    db_table='campus'
    verbose_name_plural='campuses'
  
class College(models.Model):

  
  name = models.CharField(max_length=64)
  campus = models.ForeignKey(Campus)
  
  def __unicode__(self):
    return self.name
    
  class Meta:
    db_table='college'  

    
class Program(models.Model):


  name = models.CharField(max_length=64)
  
  def __unicode__(self):
    return self.name
    
  class Meta:
    db_table='program'
  
    
class Major(models.Model):


  name = models.CharField(max_length=32, default="None")
  program = models.ForeignKey(Program)
  
  def __unicode__(self):
    if self.name:
      return u'%s (%s)' % (self.program, self.name)
    else:
      return u'%s' % (self.program)

  class Meta:
    db_table='major'
    
MONTHS = (("January", "January"), ("February", "February"), ("March", "March"), ("April", "April"),
            ("May", "May"), ("June", "June"), ("July", "July"), ("August", "August"),
            ("September", "September"), ("October", "October"), ("November", "November"), ("December", "December"))
  
class Graduation(models.Model):

  
  alumni = models.ForeignKey(Alum, related_name="grad")
  program = models.ForeignKey(Program)
  college = models.ForeignKey(College, null=True)
  month = models.CharField(max_length=10, choices=MONTHS)
  year = models.PositiveIntegerField(validators=[MinValueValidator(1963)])
  
  
  class Meta:
    db_table='graduation'
    
  def __unicode__(self):
    return u'%s (%s %d)' % (self.alumni, self.month, self.year)

class ProfileApplication(models.Model):
  """docstring for Applicant"""
  first_name = models.CharField(max_length=32)
  last_name = models.CharField(max_length=32)
  middle_name = models.CharField(max_length=32)
  email = models.EmailField(unique=True)
  mobile = models.CharField(max_length=12, null=True, blank=True)
  birthdate = models.DateField(null=True, blank=True)
  program = models.CharField(max_length=64)
  campus = models.CharField(choices=CAMPUSES, max_length=64)
  year = models.PositiveIntegerField(validators=[MinValueValidator(1963)])
  photo = models.ImageField(upload_to='applications/', default='/media/profiles/no-pic.png')
  status = models.CharField(choices=STATUS, max_length=1, default='P')
  #verified_by = models.ForeignKey(adminmodels.User)

  def send_email(self, subject, context, templates, from_email=None):
    if self.email:
      try:
        html = get_template(templates['html'])
        plaintext = get_template(templates['plaintext'])
      except KeyError:
        raise

      plaintext_content = plaintext.render(context)
      html_content = html.render(context)
      try:
        email = EmailMultiAlternatives(subject, plaintext_content, from_email, [self.email])
        email.attach_alternative(html_content, 'text/html')
        email.send()
      except:
        raise
    else:
      print "No email set!"

  def __unicode__(self):
    return u'%s %s' % (self.first_name, self.last_name)

  class Meta:
    db_table = 'profile_application'

msualumni/profiles/msuadmin/models.py
from django.db import models

# Create your models here.

msualumni/alumniadmin/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth import authenticate
from profiles.forms import AlumInfoForm, AlumGraduationForm
from profiles.models import CAMPUSES, MONTHS
#from profiles.models import Alum

class FiltersForm(forms.Form):

  first_name = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Enter First Name', 'class':'input-sm advanced'}))
  last_name = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Enter Last Name', 'class':'input-sm advanced'}))
  middle_name = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Enter Middle Name', 'class':'input-sm advanced'}))
  class_year = forms.IntegerField(required=False, label="", min_value=1963, max_value=9999, widget=forms.NumberInput(attrs={'disabled':'', 'name':'grad__year', 'placeholder':'Class Year', 'type':'number', 'class':'input-sm advanced'}))
  program = forms.CharField(required=False, max_length=64, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Program', 'name':'grad__program', 'class':'input-sm advanced'}))
  college = forms.CharField(required=False, max_length=64, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'College', 'name':'grad__college', 'class':'input-sm advanced'}))
  campus = forms.ChoiceField(required=False, label="", choices = CAMPUSES, widget=forms.Select(attrs={'disabled':'', 'placeholder':'Campus', 'name':'grad__campus', 'class':'input-sm advanced', 'type':'radio'}))
  hometown_city = forms.CharField(required=False, max_length=32,  label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Hometown City/Town', 'name':'hometown__city', 'class':'input-sm advanced'}))
  hometown_province = forms.CharField(required=False, max_length=32,  label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Hometown Province/State','name':'hometown__province',  'class':'input-sm advanced'}))
  residence_city = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Residence City/Town', 'name':'residence__city__city', 'class':'input-sm advanced'}))
  residence_province = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Residence Province/State','name':'residence__city__province', 'class':'input-sm advanced'}))
  residence_country = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Residence Country','name':'residence__city__country', 'class':'input-sm advanced'}))
  business_city = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Business City/Town', 'name':'business_address__city__city', 'class':'input-sm advanced'}))
  business_province = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Business Province/State', 'name':'business_address__city__province', 'class':'input-sm advanced'}))
  business_country = forms.CharField(required=False, max_length=32, label="", widget=forms.TextInput(attrs={'disabled':'', 'placeholder':'Business Country','name':'business_address__city__country',  'class':'input-sm advanced'}))
  

class SearchForm(forms.Form):
  
  #CHOICES = (('alumni_id', 'Alumni ID'), ('last_name','Last Name'), ('first_name', 'First Name'))
  query = forms.CharField(max_length=64, required=False, label="", widget=forms.TextInput(attrs={'placeholder':'Search for alumni', 'id':'search_field'}))
  #filter = forms.ChoiceField(choices=CHOICES, label="", widget=forms.Select(attrs={'type':'radio', 'selected':'alumni_id'}))
  

class AddProfileForm(forms.Form):

  first_name = forms.CharField(max_length=32, label="", widget=forms.TextInput(attrs={'placeholder':'Enter First Name', 'class':'input-sm form-inline'}))
  last_name = forms.CharField(max_length=32, label="", widget=forms.TextInput(attrs={'placeholder':'Enter Last Name', 'class':'input-sm'}))
  middle_name = forms.CharField(max_length=32, label="", widget=forms.TextInput(attrs={'placeholder':'Enter Middle Name', 'class':'input-sm'}))
  program = forms.CharField(max_length=64, label="", widget=forms.TextInput(attrs={'placeholder':'Program', 'class':'input-sm'}))
  college = forms.CharField(max_length=64, label="", widget=forms.TextInput(attrs={'placeholder':'College', 'class':'input-sm'}))
  campus = forms.ChoiceField(label="", choices = CAMPUSES, widget=forms.Select(attrs={'placeholder':'Campus', 'class':'input-sm', 'type':'radio'}))
  month = forms.ChoiceField(label="", choices = MONTHS,  widget=forms.Select(attrs={'placeholder':'Month', 'type':'radio', 'class':'input-sm'}))
  year = forms.IntegerField(label="", min_value=1963, max_value=9999, widget=forms.NumberInput(attrs={'placeholder':'Year', 'type':'number', 'class':'input-sm'}))
  

class LogInForm(forms.Form):
  
  
  username = forms.EmailField(max_length=64, label="", widget=forms.EmailInput(attrs={'placeholder':'Username'}))
  password = forms.CharField(max_length=32, label="", widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
  
  
  def login(self, request):
    username = self.cleaned_data.get('username')
    password = self.cleaned_data.get('password')
    
    print username
    print password
    return user

msualumni/news/forms.py
from django.forms import ModelForm, Textarea, TextInput
from models import Article

class ArticleForm(ModelForm):
	class Meta:
		model = Article
		fields = ['title', 'content']
		labels = {
			'title' : '',
			'content' : ''
		}
		widgets = {
			'title' : TextInput(attrs={'placeholder':'Headline', 'class':'input-lg'}),
			'content' : Textarea(attrs={'rows': 32, 'id':'editor'})
		}

msualumni/templates/profiles/accounts.html
{% extends 'admin_base.html' %}

msualumni/templates/profiles/accounts_base.html
{% extends 'admin_base.html' %}
{% load staticfiles %}

{% block content %}
	<div class="col-md-2">
		<ul class="nav nav-pills nav-stacked">
			{% block side_nav %}
			{% endblock side_nav %}
		</ul>
	</div>
	<div class="col-md-10">
		{% block main_content %}
		{% endblock main_content %}
	</div>
{% endblock content %}

msualumni/templates/profiles/add_profile.html
{% extends 'admin_base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
Add Alum - MSU Alumni Administration
{% endblock %}

{% block header %}
  <header style="background-image: url({% static 'images/slide1.jpg' %})">
    <div class="container">
      <table>
        <tr>
          <td class="head-icon">
            <img src="/static/images/add_user.png" height="75px"/>
          </td>
          <td class="head-content">
            <h1>Add Alum</h1>
            <h4 style="line-height: .5">Fill in the form to add an alum.</h4>
            <a href="profiles"><button type="button" class="btn btn-xs btn-warning">Back to Profiles</button></a>
          </td>
        </tr>
      </table>
    </div>
  </header>
{% endblock header %}

{% block content %}
<div class="container-fluid">
  <form method="POST" action="/admin/profiles/add" style="margin:10px 0">
    {% csrf_token %}
    <div class="col-sm-4 ">
      <fieldset id="general" style="padding:0px">
      <legend id="gen_label">Basic Alumni Information</legend>
      {% bootstrap_field form.first_name %}
      {% bootstrap_field form.last_name %}
      {% bootstrap_field form.middle_name %}
      </fieldset>
      <fieldset id="general" style="padding:0px">
      <legend id="gen_label">Graduation Information</legend>
      {% bootstrap_field form.campus %}
      {% bootstrap_field form.college %}
      {% bootstrap_field form.program %}
      <div class="col-sm-6" style="padding:0px">
        {% bootstrap_field form.month %}
      </div>
      <div class="col-sm-6">
        {% bootstrap_field form.year %}
      </div><br>
      <button id="continue" class="btn btn-danger col-sm-12">Continue</button>
      </fieldset>
    </div>
  </form>
</div>
{% endblock content %}

msualumni/templates/profiles/advanced_search.html
{% extends 'admin_base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
  MSU Alumni Admin - Profiles
{% endblock title %}

{% block header %}
  <header style="background-image: url({% static 'images/slide1.jpg' %})">
    <div class="container">
      <h1>
        Advanced Searching
      </h1>
      <a href="/admin/profiles">
          <span class="glyphicon glyphicon-user"></span>
          Back to Profiles
      </a>
    </div>
  </header>
{% endblock header %}
{% block content %}
  <div class="container-fluid"  style="min-height:420px">
    <div class="col-md-3">
      <form autocomplete="on" method="get" action="/admin/profiles/advanced">
      <table width="100%">
          <tr><td></td><td><strong>Full Name</strong><br></td></tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_first_name">
            </td>
            <td>
              {% bootstrap_field form.first_name %}
            </td>
          </tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_middle_name">
            </td>
            <td>
              {% bootstrap_field form.middle_name %}
            </td>
          </tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_last_name">
            </td>
            <td>
              {% bootstrap_field form.last_name %}
            </td>
          </tr>
          <tr><td></td><td><strong>Graduation</strong><br></td></tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_class_year">
            </td>
            <td>
              {% bootstrap_field form.class_year %}
            </td>
          </tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_program">
            </td>
            <td>
              {% bootstrap_field form.program %}
            </td>
          </tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_college">
            </td>
            <td>
              {% bootstrap_field form.college %}
            </td>
          </tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_campus">
            </td>
            <td>
              {% bootstrap_field form.campus %}
            </td>
          </tr>
          <tr><td></td><td><strong>Hometown</strong><br></td></tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_hometown_city">
            </td>
            <td>
              {% bootstrap_field form.hometown_city %}
            </td>
          </tr>
          <tr>
            <td class="ticker">
              <input type="checkbox" class="filter_pick" data-toggle="#id_hometown_province">
            </td>
            <td>
              {% bootstrap_field form.hometown_province %}
            </td>
          </tr>
        </table>          
        
        <a href="#" id="more">Show more</a>
          
        <div id="more_filters" style="display:none">
          <table width="100%" style="margin:0">
            <tr><td></td><td><strong>Residence</strong><br></td></tr>
            <tr>
              <td class="ticker">
                <input type="checkbox" class="filter_pick" data-toggle="#id_residence_city">
              </td>
              <td>
                {% bootstrap_field form.residence_city %}
              </td>
            </tr>
            <tr>
              <td class="ticker">
                <input type="checkbox" class="filter_pick" data-toggle="#id_residence_province">
              </td>
              <td>
                {% bootstrap_field form.residence_province %}
              </td>
            </tr>
            <tr>
              <td class="ticker">
                <input type="checkbox" class="filter_pick" data-toggle="#id_residence_country">
              </td>
              <td>
                {% bootstrap_field form.residence_country %}
              </td>
            </tr>
            <tr><td></td><td><strong>Business Address</strong><br></td></tr>
            <tr>
              <td class="ticker">
                <input type="checkbox" class="filter_pick" data-toggle="#id_business_city">
              </td>
              <td>
                {% bootstrap_field form.business_city %}
              </td>
            </tr>
            <tr>
              <td class="ticker">
                <input type="checkbox" class="filter_pick" data-toggle="#id_business_province">
              </td>
              <td>
                {% bootstrap_field form.business_province %}
              </td>
            </tr>
            <tr>
              <td class="ticker">
                <input type="checkbox" class="filter_pick" data-toggle="#id_business_country">
              </td>
              <td>
                {% bootstrap_field form.business_country %}
              </td>
            </tr>
          </table>
        </div>
        <br>
        <button class="btn btn-primary col-md-12">Let's Go!</button>
      </form>
    </div>
    <div class="col-md-9" >
      {% if not object_list %}
      <h4>
        Choose your filters from the right.<br>
        <small>Click the checkbox to enable the filter and type in your query</small>
      </h4>
      {% else %}
        {% include 'results_table.html' %}
      {% endif %}
    </div>
  </div>
  <!-- <div class="col-sm-4">
    <div id="profile">
    </div>
  </div> -->
{% endblock content %}

{% block scripts %}
  <script type="text/javascript" src="/static/js/simple_search.js"></script>
  <script type="text/javascript" src="{% static 'js/admin.js' %}"></script>
{% endblock scripts %}

msualumni/templates/profiles/applicant_profile.html
<div class="modal fade in" id="modal_alert" tabindex="-1" role="dialog"  aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    	<div class="modal-header" >
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h5 class="modal-title" style="color:#111111" >{{applicant.first_name}} {{applicant.middle_name}} {{applicant.last_name}}</h5>
	      </div>
    	<div class="modal-body">
    		<img src={% url applicant.photo %)>
    	</div>
    </div>
  </div>
</div>

msualumni/templates/profiles/approval_actions.html
<div class="dropdown">
  <button class="btn btn-sm bdropdown-toggle" type="button" id="action_taken" data-toggle="dropdown">
    Choose Action
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="action_taken">
    {% if user.is_superuser %}
      <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:commit('approve')">Approve</a></li>
    {% else %}
      <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:commit('recommend')">Recommend Approval</a></li>
    {% endif %}
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Ask more info</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Delete</a></li>
  </ul>
</div>

msualumni/templates/profiles/profiles.html
{% extends 'admin/profiles_base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block title %}
  Profiles - MSU Alumni Admin
{% endblock title %}

{% block header %}
  <header style="background-image: url({% static 'images/slide1.jpg' %})">
    <div class="container">
      <img src="{% static 'images/cap.png' %}" height="75px" style="float:left; margin-right:8px; margin-top:24px"/>
      {% include 'simple_search.html' %}
      <h1>
        Alumni Profiles
      </h1>
      <a href="/admin/profiles/add">
          <span class="glyphicon glyphicon-user"></span>
          Add profile
      </a>
      &nbsp;
      <a href="#" id="upload_csv" data-target="#upload_csv_modal" data-toggle="modal">
        <span class="glyphicon glyphicon-upload"></span>
        Add from csv file
      </a>
      <br>
      <a href="/admin/profiles/advanced">
        <span class="glyphicon glyphicon-search"></span>
        Advanced search with more filters
      </a>
      {% include 'upload_csv_modal.html' %}
    </div>
  </header>
{% endblock header %}

{% block side_nav %}
  <li class="active"><a href="/admin/profiles">Profiles</a></li>
  <li>
    <a href="/admin/profiles/requests">
      Requests
      <label class="label label-primary">
        {{ request_count }}
      </label>
    </a>
  </li>
{% endblock side_nav %}
{% block scripts %}
  <script type="text/javascript" src="/static/js/simple_search.js"></script>
  <script type="text/javascript" src="{% static 'js/admin.js' %}"></script>
{% endblock scripts %}